server:
  port: 8989
spring:
  application:
    name: SENTINEL
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      #作为 nacos client的注册地址
      discoverys:
        #也可以不写  默认${spring.cloud.nacos.server-addr}
        server-addr: 127.0.0.1:8848
        #也可以不写  ${spring.application.name}
        service: SENTINEL
    # 开启 sentinel 保护
    sentinel:
      enabled: true
      transport:
        # 指定 sentinel dashboard web 地址
        dashboard: 127.0.0.1:9090
        # 指定 sentinel 组件与 sentinel dashboard 组件通信地址
        port: 9999